-- ============================================
-- MAIN ENTRY POINT: Obfuscator API
-- ============================================
-- Complete integration of all components

local Lexer = require(script.Parent.parser.lexer)
local Parser = require(script.Parent.parser.parser)
local BytecodeCompiler = require(script.Parent.vm.bytecode_compiler)
local VMInterpreter = require(script.Parent.vm.vm_interpreter)
local Pipeline = require(script.Parent.obfuscation.pipeline)

local Obfuscator = {}
Obfuscator.__index = Obfuscator

function Obfuscator.new(config)
    local self = setmetatable({}, Obfuscator)
    
    self.config = config or {}
    self.config.obfuscation_level = self.config.obfuscation_level or "high"
    self.config.vm_enabled = self.config.vm_enabled ~= false
    self.config.anti_tamper = self.config.anti_tamper ~= false
    self.config.string_encryption = self.config.string_encryption ~= false
    self.config.constant_obfuscation = self.config.constant_obfuscation ~= false
    self.config.identifier_mangling = self.config.identifier_mangling ~= false
    self.config.control_flow_flattening = self.config.control_flow_flattening ~= false
    self.config.seed = self.config.seed or 0 -- 0 = random
    
    if self.config.seed == 0 then
        self.config.seed = math.random(1, 2147483647)
    end
    
    self.pipeline = Pipeline.new({
        level = self.config.obfuscation_level,
        string_encryption = self.config.string_encryption,
        constant_obfuscation = self.config.constant_obfuscation,
        identifier_mangling = self.config.identifier_mangling,
        control_flow = self.config.control_flow_flattening,
        seed = self.config.seed,
    })
    
    return self
end

function Obfuscator:obfuscate(source_code)
    -- Stage 1: Lexical Analysis
    local lexer = Lexer.new(source_code)
    local tokens = lexer:tokenize()
    
    -- Stage 2: Parsing (AST Generation)
    local parser = Parser.new(tokens)
    local ast = parser:parse()
    
    -- Stage 3: Obfuscation Pipeline
    local obfuscated_ast = self.pipeline:execute(ast)
    
    -- Stage 4: Bytecode Compilation
    local compiler = BytecodeCompiler.new()
    local bytecode = compiler:compile(obfuscated_ast)
    local constants = compiler:get_constants()
    
    -- Stage 5: VM Wrapper Generation
    local wrapper = self:generate_vm_wrapper(bytecode, constants)
    
    return wrapper
end

function Obfuscator:generate_vm_wrapper(bytecode, constants)
    local wrapper = [[
-- ============================================
-- OBFUSCATED CODE - DO NOT MODIFY
-- ============================================
-- Generated by Roblox Luau VM Obfuscator
-- Protection Level: ]] .. self.config.obfuscation_level .. [[

local _VM = {}
_VM.__index = _VM

-- Bytecode data (encrypted)
local _bytecode = "]] .. self:encode_bytecode(bytecode) .. [["
local _constants = {
]] .. self:encode_constants(constants) .. [[
}

-- String decryption (for string_obfuscator)
local _string_key = {]] .. table.concat(self.pipeline:get_string_obfuscator().decryption_key, ",") .. [[}
local _decrypted_cache = {}

local function _decrypt_string(id, encrypted_bytes)
    if _decrypted_cache[id] then return _decrypted_cache[id] end
    local decrypted = ""
    for i = 1, #encrypted_bytes do
        local key_byte = _string_key[(i % #_string_key) + 1]
        local char = encrypted_bytes[i] ~ key_byte
        decrypted = decrypted .. string.char(char)
    end
    _decrypted_cache[id] = decrypted
    return decrypted
end

-- Stack machine implementation
function _VM:new()
    local instance = setmetatable({}, _VM)
    instance.stack = {}
    instance.pc = 1
    instance.globals = {}
    instance.locals = {}
    instance.running = true
    return instance
end

function _VM:push(value)
    table.insert(self.stack, value)
end

function _VM:pop()
    if #self.stack == 0 then error("Stack underflow") end
    return table.remove(self.stack)
end

function _VM:peek()
    if #self.stack == 0 then error("Stack empty") end
    return self.stack[#self.stack]
end

function _VM:execute()
    while self.pc <= #_bytecode and self.running do
        local opcode = string.byte(_bytecode, self.pc)
        self.pc = self.pc + 1
        
        if opcode == 0x01 then
            -- LOAD_CONST
            local idx = string.byte(_bytecode, self.pc) + (string.byte(_bytecode, self.pc + 1) * 256)
            self.pc = self.pc + 2
            self:push(_constants[idx])
        
        elseif opcode == 0x02 then
            -- LOAD_VAR
            local idx = string.byte(_bytecode, self.pc) + (string.byte(_bytecode, self.pc + 1) * 256)
            self.pc = self.pc + 2
            self:push(self.locals[idx])
        
        elseif opcode == 0x03 then
            -- STORE_VAR
            local idx = string.byte(_bytecode, self.pc) + (string.byte(_bytecode, self.pc + 1) * 256)
            self.pc = self.pc + 2
            self.locals[idx] = self:pop()
        
        elseif opcode == 0x10 then
            local b = self:pop()
            local a = self:pop()
            self:push(a + b)
        
        elseif opcode == 0x11 then
            local b = self:pop()
            local a = self:pop()
            self:push(a - b)
        
        elseif opcode == 0x12 then
            local b = self:pop()
            local a = self:pop()
            self:push(a * b)
        
        elseif opcode == 0x13 then
            local b = self:pop()
            local a = self:pop()
            if b == 0 then error("Division by zero") end
            self:push(a / b)
        
        elseif opcode == 0x20 then
            local b = self:pop()
            local a = self:pop()
            self:push(a == b)
        
        elseif opcode == 0x30 then
            local b = self:pop()
            local a = self:pop()
            self:push(a and b)
        
        elseif opcode == 0x31 then
            local b = self:pop()
            local a = self:pop()
            self:push(a or b)
        
        elseif opcode == 0x32 then
            local a = self:pop()
            self:push(not a)
        
        elseif opcode == 0x50 then
            -- CALL
            local arg_count = string.byte(_bytecode, self.pc)
            self.pc = self.pc + 1
            local args = {}
            for i = 1, arg_count do
                table.insert(args, 1, self:pop())
            end
            local func = self:pop()
            local results = {func(unpack(args))}
            for _, result in ipairs(results) do
                self:push(result)
            end
        
        elseif opcode == 0x51 then
            self.running = false
            return self:pop()
        
        elseif opcode == 0xFF then
            self.running = false
            break
        end
    end
    return nil
end

-- Initialize and execute
local _vm_instance = _VM:new()
return _vm_instance:execute()
]]
    
    return wrapper
end

function Obfuscator:encode_bytecode(bytecode)
    -- XOR encode bytecode for extra protection
    local encoded = ""
    local seed = self.config.seed
    for i = 1, #bytecode do
        local byte = string.byte(bytecode, i)
        local key = (seed + i) % 256
        encoded = encoded .. string.format("%02x", byte ~ key)
    end
    return encoded
end

function Obfuscator:encode_constants(constants)
    local result = ""
    for i, const in ipairs(constants) do
        if type(const) == "number" then
            result = result .. (i > 1 and "," or "") .. "    [" .. i .. "] = " .. tostring(const)
        elseif type(const) == "string" then
            result = result .. (i > 1 and "," or "") .. "    [" .. i .. "] = \"" .. const:gsub('"', '\\"') .. "\""
        elseif type(const) == "boolean" then
            result = result .. (i > 1 and "," or "") .. "    [" .. i .. "] = " .. (const and "true" or "false")
        elseif const == nil then
            result = result .. (i > 1 and "," or "") .. "    [" .. i .. "] = nil"
        end
    end
    return result .. "\n"
end

function Obfuscator.obfuscate(source_code, config)
    local obf = Obfuscator.new(config)
    return obf:obfuscate(source_code)
end

return Obfuscator